// This file is auto-generated by @hey-api/openapi-ts

export const BoundingBoxModelSchema = {
    properties: {
        x: {
            type: 'integer',
            title: 'X'
        },
        y: {
            type: 'integer',
            title: 'Y'
        },
        width: {
            type: 'integer',
            title: 'Width'
        },
        height: {
            type: 'integer',
            title: 'Height'
        }
    },
    type: 'object',
    required: [
        'x',
        'y',
        'width',
        'height'
    ],
    title: 'BoundingBoxModel'
} as const;

export const CreateJobRequestSchema = {
    properties: {
        job_type: {
            $ref: '#/components/schemas/JobType'
        },
        external_id: {
            type: 'string',
            title: 'External Id',
            description: 'Project identifier'
        },
        video_url: {
            type: 'string',
            title: 'Video Url',
            description: 'URL or path to video file'
        },
        callback_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Callback Url',
            description: 'Callback URL for job completion notifications'
        },
        params: {
            anyOf: [
                {
                    $ref: '#/components/schemas/ObjectDetectParams'
                },
                {
                    $ref: '#/components/schemas/SceneDetectParams'
                },
                {
                    $ref: '#/components/schemas/TranscribeParams'
                }
            ],
            title: 'Params'
        }
    },
    type: 'object',
    required: [
        'job_type',
        'external_id',
        'video_url'
    ],
    title: 'CreateJobRequest'
} as const;

export const CreateJobResponseSchema = {
    properties: {
        job_id: {
            type: 'string',
            title: 'Job Id'
        },
        job_type: {
            $ref: '#/components/schemas/JobType'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        queue_position: {
            type: 'integer',
            title: 'Queue Position'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        callback_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Callback Url'
        }
    },
    type: 'object',
    required: [
        'job_id',
        'job_type',
        'status',
        'queue_position',
        'message'
    ],
    title: 'CreateJobResponse'
} as const;

export const DetectionFrameModelSchema = {
    properties: {
        frame_idx: {
            type: 'integer',
            title: 'Frame Idx'
        },
        timestamp: {
            type: 'number',
            title: 'Timestamp'
        },
        objects: {
            items: {
                $ref: '#/components/schemas/DetectionObjectModel'
            },
            type: 'array',
            title: 'Objects'
        }
    },
    type: 'object',
    required: [
        'frame_idx',
        'timestamp',
        'objects'
    ],
    title: 'DetectionFrameModel'
} as const;

export const DetectionObjectModelSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        class_name: {
            type: 'string',
            title: 'Class Name'
        },
        confidence: {
            type: 'number',
            title: 'Confidence'
        },
        bbox: {
            $ref: '#/components/schemas/BoundingBoxModel'
        },
        thumbnail: {
            type: 'string',
            title: 'Thumbnail'
        }
    },
    type: 'object',
    required: [
        'id',
        'class_name',
        'confidence',
        'bbox',
        'thumbnail'
    ],
    title: 'DetectionObjectModel'
} as const;

export const DetectionResultsModelSchema = {
    properties: {
        result_type: {
            type: 'string',
            const: 'object_detect',
            title: 'Result Type',
            default: 'object_detect'
        },
        version: {
            type: 'string',
            title: 'Version'
        },
        metadata: {
            $ref: '#/components/schemas/ResultsMetadataModel'
        },
        frames: {
            items: {
                $ref: '#/components/schemas/DetectionFrameModel'
            },
            type: 'array',
            title: 'Frames'
        }
    },
    type: 'object',
    required: [
        'version',
        'metadata',
        'frames'
    ],
    title: 'DetectionResultsModel'
} as const;

export const DetectionStatisticsModelSchema = {
    properties: {
        total_detections: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total Detections'
        },
        person_detections: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Person Detections'
        },
        person_with_face: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Person With Face'
        },
        person_without_face: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Person Without Face'
        },
        other_detections: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Other Detections'
        },
        class_counts: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'integer'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Class Counts'
        }
    },
    type: 'object',
    title: 'DetectionStatisticsModel'
} as const;

export const DiarizationSegmentModelSchema = {
    properties: {
        start: {
            type: 'number',
            title: 'Start'
        },
        end: {
            type: 'number',
            title: 'End'
        },
        speaker: {
            type: 'string',
            title: 'Speaker'
        }
    },
    type: 'object',
    required: [
        'start',
        'end',
        'speaker'
    ],
    title: 'DiarizationSegmentModel'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HealthResponseSchema = {
    properties: {
        version: {
            type: 'string',
            title: 'Version'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        timestamp: {
            type: 'string',
            title: 'Timestamp'
        },
        job_stats: {
            anyOf: [
                {
                    $ref: '#/components/schemas/JobStats'
                },
                {
                    type: 'null'
                }
            ]
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        }
    },
    type: 'object',
    required: [
        'version',
        'status',
        'timestamp'
    ],
    title: 'HealthResponse'
} as const;

export const JobCompletedWebhookSchema = {
    properties: {
        job_id: {
            type: 'string',
            title: 'Job Id'
        },
        external_id: {
            type: 'string',
            title: 'External Id'
        },
        job_type: {
            type: 'string',
            title: 'Job Type'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        timestamp: {
            type: 'string',
            format: 'date-time',
            title: 'Timestamp'
        }
    },
    type: 'object',
    required: [
        'job_id',
        'external_id',
        'job_type',
        'status',
        'timestamp'
    ],
    title: 'JobCompletedWebhook'
} as const;

export const JobResultsResponseSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        },
        job_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Job Type'
        },
        data: {
            anyOf: [
                {
                    oneOf: [
                        {
                            $ref: '#/components/schemas/DetectionResultsModel'
                        },
                        {
                            $ref: '#/components/schemas/SceneDetectResultsModel'
                        },
                        {
                            $ref: '#/components/schemas/TranscribeResultsModel'
                        }
                    ],
                    discriminator: {
                        propertyName: 'result_type',
                        mapping: {
                            object_detect: '#/components/schemas/DetectionResultsModel',
                            scene_detect: '#/components/schemas/SceneDetectResultsModel',
                            transcribe: '#/components/schemas/TranscribeResultsModel'
                        }
                    }
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        }
    },
    type: 'object',
    required: [
        'status'
    ],
    title: 'JobResultsResponse'
} as const;

export const JobStatsSchema = {
    properties: {
        queued: {
            type: 'integer',
            title: 'Queued'
        },
        processing: {
            type: 'integer',
            title: 'Processing'
        },
        completed: {
            type: 'integer',
            title: 'Completed'
        },
        failed: {
            type: 'integer',
            title: 'Failed'
        }
    },
    type: 'object',
    required: [
        'queued',
        'processing',
        'completed',
        'failed'
    ],
    title: 'JobStats'
} as const;

export const JobStatusResponseSchema = {
    properties: {
        job_id: {
            type: 'string',
            title: 'Job Id'
        },
        external_id: {
            type: 'string',
            title: 'External Id'
        },
        job_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Job Type'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        progress: {
            type: 'number',
            title: 'Progress'
        },
        queue_position: {
            type: 'integer',
            title: 'Queue Position',
            default: 0
        },
        estimated_wait_time: {
            type: 'string',
            title: 'Estimated Wait Time',
            default: '00:00:00'
        },
        start_time: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Time'
        },
        end_time: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Time'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        }
    },
    type: 'object',
    required: [
        'job_id',
        'external_id',
        'status',
        'progress'
    ],
    title: 'JobStatusResponse'
} as const;

export const JobTypeSchema = {
    type: 'string',
    enum: [
        'object_detect',
        'scene_detect',
        'transcribe'
    ],
    title: 'JobType'
} as const;

export const ObjectDetectParamsSchema = {
    properties: {
        similarity_threshold: {
            type: 'number',
            maximum: 1,
            minimum: 0,
            title: 'Similarity Threshold',
            description: 'Similarity threshold for object tracking',
            default: 0.5
        },
        analysis_fps: {
            type: 'number',
            maximum: 60,
            exclusiveMinimum: 0,
            title: 'Analysis Fps',
            description: 'Frames per second to analyse (default 1)',
            default: 1
        }
    },
    type: 'object',
    title: 'ObjectDetectParams'
} as const;

export const ProcessingMetadataModelSchema = {
    properties: {
        start_time: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Time'
        },
        end_time: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Time'
        },
        duration_seconds: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration Seconds'
        },
        frames_processed: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Frames Processed'
        },
        frames_with_detections: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Frames With Detections'
        },
        processing_speed: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Processing Speed'
        },
        detection_statistics: {
            anyOf: [
                {
                    $ref: '#/components/schemas/DetectionStatisticsModel'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'ProcessingMetadataModel'
} as const;

export const ResultsMetadataModelSchema = {
    properties: {
        video: {
            $ref: '#/components/schemas/VideoMetadataModel'
        },
        sprite: {
            $ref: '#/components/schemas/SpriteMetadataModel'
        },
        processing: {
            $ref: '#/components/schemas/ProcessingMetadataModel'
        }
    },
    type: 'object',
    required: [
        'video',
        'sprite',
        'processing'
    ],
    title: 'ResultsMetadataModel'
} as const;

export const SceneDetectParamsSchema = {
    properties: {
        threshold: {
            type: 'number',
            exclusiveMinimum: 0,
            title: 'Threshold',
            description: 'Content detection sensitivity threshold',
            default: 30
        }
    },
    type: 'object',
    title: 'SceneDetectParams'
} as const;

export const SceneDetectResultsModelSchema = {
    properties: {
        result_type: {
            type: 'string',
            const: 'scene_detect',
            title: 'Result Type',
            default: 'scene_detect'
        },
        total_scenes: {
            type: 'integer',
            title: 'Total Scenes'
        },
        scenes: {
            items: {
                $ref: '#/components/schemas/SceneInfoModel'
            },
            type: 'array',
            title: 'Scenes'
        },
        sprite_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sprite Url'
        },
        sprite_fragments: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sprite Fragments'
        }
    },
    type: 'object',
    required: [
        'total_scenes',
        'scenes'
    ],
    title: 'SceneDetectResultsModel'
} as const;

export const SceneInfoModelSchema = {
    properties: {
        scene_id: {
            type: 'integer',
            title: 'Scene Id'
        },
        start_time: {
            type: 'string',
            title: 'Start Time'
        },
        end_time: {
            type: 'string',
            title: 'End Time'
        },
        start_seconds: {
            type: 'number',
            title: 'Start Seconds'
        },
        end_seconds: {
            type: 'number',
            title: 'End Seconds'
        },
        duration_seconds: {
            type: 'number',
            title: 'Duration Seconds'
        },
        sprite_fragment: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sprite Fragment'
        }
    },
    type: 'object',
    required: [
        'scene_id',
        'start_time',
        'end_time',
        'start_seconds',
        'end_seconds',
        'duration_seconds'
    ],
    title: 'SceneInfoModel'
} as const;

export const SpeakerSummaryModelSchema = {
    properties: {
        label: {
            type: 'string',
            title: 'Label'
        },
        total_speaking_time_sec: {
            type: 'number',
            title: 'Total Speaking Time Sec'
        }
    },
    type: 'object',
    required: [
        'label',
        'total_speaking_time_sec'
    ],
    title: 'SpeakerSummaryModel'
} as const;

export const SpriteMetadataModelSchema = {
    properties: {
        url: {
            type: 'string',
            title: 'Url'
        },
        thumbnail_size: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Thumbnail Size'
        }
    },
    type: 'object',
    required: [
        'url',
        'thumbnail_size'
    ],
    title: 'SpriteMetadataModel'
} as const;

export const TranscribeParamsSchema = {
    properties: {
        model_size: {
            type: 'string',
            title: 'Model Size',
            description: 'Whisper model size (tiny, base, small, medium, large-v2, large-v3)',
            default: 'small'
        },
        device: {
            type: 'string',
            title: 'Device',
            description: 'Inference device (cpu or cuda)',
            default: 'cpu'
        },
        compute_type: {
            type: 'string',
            title: 'Compute Type',
            description: 'Quantisation type (int8, float16, float32)',
            default: 'int8'
        },
        language: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Language',
            description: 'ISO-639-1 language code, or null for auto-detection'
        },
        diarization_enabled: {
            type: 'boolean',
            title: 'Diarization Enabled',
            description: 'Whether to run speaker diarization',
            default: true
        },
        num_speakers: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Num Speakers',
            description: 'Exact number of speakers (overrides min/max)'
        },
        min_speakers: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Min Speakers',
            description: 'Minimum number of speakers hint'
        },
        max_speakers: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Speakers',
            description: 'Maximum number of speakers hint'
        }
    },
    type: 'object',
    title: 'TranscribeParams'
} as const;

export const TranscribeResultsModelSchema = {
    properties: {
        result_type: {
            type: 'string',
            const: 'transcribe',
            title: 'Result Type',
            default: 'transcribe'
        },
        metadata: {
            $ref: '#/components/schemas/TranscriptionMetadataModel'
        },
        segments: {
            items: {
                $ref: '#/components/schemas/TranscriptSegmentModel'
            },
            type: 'array',
            title: 'Segments'
        },
        speakers: {
            items: {
                $ref: '#/components/schemas/SpeakerSummaryModel'
            },
            type: 'array',
            title: 'Speakers'
        },
        diarization: {
            items: {
                $ref: '#/components/schemas/DiarizationSegmentModel'
            },
            type: 'array',
            title: 'Diarization'
        }
    },
    type: 'object',
    required: [
        'metadata',
        'segments',
        'speakers',
        'diarization'
    ],
    title: 'TranscribeResultsModel'
} as const;

export const TranscriptSegmentModelSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        start: {
            type: 'number',
            title: 'Start'
        },
        end: {
            type: 'number',
            title: 'End'
        },
        speaker: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Speaker'
        },
        text: {
            type: 'string',
            title: 'Text'
        },
        confidence: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Confidence'
        },
        words: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/WordModel'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Words'
        }
    },
    type: 'object',
    required: [
        'id',
        'start',
        'end',
        'text'
    ],
    title: 'TranscriptSegmentModel'
} as const;

export const TranscriptionMetadataModelSchema = {
    properties: {
        engine: {
            type: 'string',
            title: 'Engine'
        },
        asr_backend: {
            type: 'string',
            title: 'Asr Backend',
            default: 'faster-whisper'
        },
        diarization_backend: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Diarization Backend'
        },
        device: {
            type: 'string',
            title: 'Device'
        },
        compute_type: {
            type: 'string',
            title: 'Compute Type'
        },
        asr_model: {
            type: 'string',
            title: 'Asr Model'
        },
        language: {
            type: 'string',
            title: 'Language'
        },
        audio_duration_sec: {
            type: 'number',
            title: 'Audio Duration Sec'
        },
        processing_time_sec: {
            type: 'number',
            title: 'Processing Time Sec'
        }
    },
    type: 'object',
    required: [
        'engine',
        'device',
        'compute_type',
        'asr_model',
        'language',
        'audio_duration_sec',
        'processing_time_sec'
    ],
    title: 'TranscriptionMetadataModel'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;

export const VideoMetadataModelSchema = {
    properties: {
        fps: {
            type: 'number',
            title: 'Fps'
        },
        frame_count: {
            type: 'integer',
            title: 'Frame Count'
        },
        width: {
            type: 'integer',
            title: 'Width'
        },
        height: {
            type: 'integer',
            title: 'Height'
        },
        source: {
            type: 'string',
            title: 'Source'
        }
    },
    type: 'object',
    required: [
        'fps',
        'frame_count',
        'width',
        'height',
        'source'
    ],
    title: 'VideoMetadataModel'
} as const;

export const WordModelSchema = {
    properties: {
        word: {
            type: 'string',
            title: 'Word'
        },
        start: {
            type: 'number',
            title: 'Start'
        },
        end: {
            type: 'number',
            title: 'End'
        },
        probability: {
            type: 'number',
            title: 'Probability'
        }
    },
    type: 'object',
    required: [
        'word',
        'start',
        'end',
        'probability'
    ],
    title: 'WordModel'
} as const;
