// This file is auto-generated by @hey-api/openapi-ts

export const AnalysisRequestSchema = {
    properties: {
        external_id: {
            type: 'string',
            title: 'External Id',
            description: 'Project identifier'
        },
        video_url: {
            type: 'string',
            title: 'Video Url',
            description: 'URL or path to video file'
        },
        similarity_threshold: {
            type: 'number',
            maximum: 1,
            minimum: 0,
            title: 'Similarity Threshold',
            description: 'Similarity threshold for object tracking',
            default: 0.5
        },
        callback_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Callback Url',
            description: 'Callback URL for job completion notifications'
        }
    },
    type: 'object',
    required: [
        'external_id',
        'video_url'
    ],
    title: 'AnalysisRequest'
} as const;

export const AnalysisResponseSchema = {
    properties: {
        job_id: {
            type: 'string',
            title: 'Job Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        queue_position: {
            type: 'integer',
            title: 'Queue Position'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        callback_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Callback Url'
        }
    },
    type: 'object',
    required: [
        'job_id',
        'status',
        'queue_position',
        'message'
    ],
    title: 'AnalysisResponse'
} as const;

export const BoundingBoxModelSchema = {
    properties: {
        x: {
            type: 'integer',
            title: 'X'
        },
        y: {
            type: 'integer',
            title: 'Y'
        },
        width: {
            type: 'integer',
            title: 'Width'
        },
        height: {
            type: 'integer',
            title: 'Height'
        }
    },
    type: 'object',
    required: [
        'x',
        'y',
        'width',
        'height'
    ],
    title: 'BoundingBoxModel'
} as const;

export const DetectionFrameModelSchema = {
    properties: {
        frame_idx: {
            type: 'integer',
            title: 'Frame Idx'
        },
        timestamp: {
            type: 'number',
            title: 'Timestamp'
        },
        objects: {
            items: {
                $ref: '#/components/schemas/DetectionObjectModel'
            },
            type: 'array',
            title: 'Objects'
        }
    },
    type: 'object',
    required: [
        'frame_idx',
        'timestamp',
        'objects'
    ],
    title: 'DetectionFrameModel'
} as const;

export const DetectionObjectModelSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        class_name: {
            type: 'string',
            title: 'Class Name'
        },
        confidence: {
            type: 'number',
            title: 'Confidence'
        },
        bbox: {
            $ref: '#/components/schemas/BoundingBoxModel'
        },
        thumbnail: {
            type: 'string',
            title: 'Thumbnail'
        }
    },
    type: 'object',
    required: [
        'id',
        'class_name',
        'confidence',
        'bbox',
        'thumbnail'
    ],
    title: 'DetectionObjectModel'
} as const;

export const DetectionResultsModelSchema = {
    properties: {
        version: {
            type: 'string',
            title: 'Version'
        },
        metadata: {
            $ref: '#/components/schemas/ResultsMetadataModel'
        },
        frames: {
            items: {
                $ref: '#/components/schemas/DetectionFrameModel'
            },
            type: 'array',
            title: 'Frames'
        }
    },
    type: 'object',
    required: [
        'version',
        'metadata',
        'frames'
    ],
    title: 'DetectionResultsModel'
} as const;

export const DetectionStatisticsModelSchema = {
    properties: {
        total_detections: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total Detections'
        },
        person_detections: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Person Detections'
        },
        person_with_face: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Person With Face'
        },
        person_without_face: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Person Without Face'
        },
        other_detections: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Other Detections'
        },
        class_counts: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'integer'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Class Counts'
        }
    },
    type: 'object',
    title: 'DetectionStatisticsModel'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HealthResponseSchema = {
    properties: {
        version: {
            type: 'string',
            title: 'Version'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        timestamp: {
            type: 'string',
            title: 'Timestamp'
        },
        job_stats: {
            anyOf: [
                {
                    $ref: '#/components/schemas/JobStats'
                },
                {
                    type: 'null'
                }
            ]
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        }
    },
    type: 'object',
    required: [
        'version',
        'status',
        'timestamp'
    ],
    title: 'HealthResponse'
} as const;

export const JobCompletedWebhookSchema = {
    properties: {
        job_id: {
            type: 'string',
            title: 'Job Id'
        },
        external_id: {
            type: 'string',
            title: 'External Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        timestamp: {
            type: 'string',
            format: 'date-time',
            title: 'Timestamp'
        }
    },
    type: 'object',
    required: [
        'job_id',
        'external_id',
        'status',
        'timestamp'
    ],
    title: 'JobCompletedWebhook'
} as const;

export const JobResultsResponseSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        },
        data: {
            anyOf: [
                {
                    $ref: '#/components/schemas/DetectionResultsModel'
                },
                {
                    type: 'null'
                }
            ]
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        }
    },
    type: 'object',
    required: [
        'status'
    ],
    title: 'JobResultsResponse'
} as const;

export const JobStatsSchema = {
    properties: {
        queued: {
            type: 'integer',
            title: 'Queued'
        },
        processing: {
            type: 'integer',
            title: 'Processing'
        },
        completed: {
            type: 'integer',
            title: 'Completed'
        },
        failed: {
            type: 'integer',
            title: 'Failed'
        }
    },
    type: 'object',
    required: [
        'queued',
        'processing',
        'completed',
        'failed'
    ],
    title: 'JobStats'
} as const;

export const JobStatusResponseSchema = {
    properties: {
        job_id: {
            type: 'string',
            title: 'Job Id'
        },
        external_id: {
            type: 'string',
            title: 'External Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        progress: {
            type: 'number',
            title: 'Progress'
        },
        queue_position: {
            type: 'integer',
            title: 'Queue Position',
            default: 0
        },
        estimated_wait_time: {
            type: 'string',
            title: 'Estimated Wait Time',
            default: '00:00:00'
        },
        start_time: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Time'
        },
        end_time: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Time'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        }
    },
    type: 'object',
    required: [
        'job_id',
        'external_id',
        'status',
        'progress'
    ],
    title: 'JobStatusResponse'
} as const;

export const ProcessingMetadataModelSchema = {
    properties: {
        start_time: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Time'
        },
        end_time: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Time'
        },
        duration_seconds: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration Seconds'
        },
        frames_processed: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Frames Processed'
        },
        frames_with_detections: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Frames With Detections'
        },
        processing_speed: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Processing Speed'
        },
        detection_statistics: {
            anyOf: [
                {
                    $ref: '#/components/schemas/DetectionStatisticsModel'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'ProcessingMetadataModel'
} as const;

export const ResultsMetadataModelSchema = {
    properties: {
        video: {
            $ref: '#/components/schemas/VideoMetadataModel'
        },
        sprite: {
            $ref: '#/components/schemas/SpriteMetadataModel'
        },
        processing: {
            $ref: '#/components/schemas/ProcessingMetadataModel'
        }
    },
    type: 'object',
    required: [
        'video',
        'sprite',
        'processing'
    ],
    title: 'ResultsMetadataModel'
} as const;

export const SpriteMetadataModelSchema = {
    properties: {
        path: {
            type: 'string',
            title: 'Path'
        },
        thumbnail_size: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Thumbnail Size'
        }
    },
    type: 'object',
    required: [
        'path',
        'thumbnail_size'
    ],
    title: 'SpriteMetadataModel'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;

export const VideoMetadataModelSchema = {
    properties: {
        fps: {
            type: 'number',
            title: 'Fps'
        },
        frame_count: {
            type: 'integer',
            title: 'Frame Count'
        },
        width: {
            type: 'integer',
            title: 'Width'
        },
        height: {
            type: 'integer',
            title: 'Height'
        },
        source: {
            type: 'string',
            title: 'Source'
        }
    },
    type: 'object',
    required: [
        'fps',
        'frame_count',
        'width',
        'height',
        'source'
    ],
    title: 'VideoMetadataModel'
} as const;
