// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client/index.js';
import type { CreateJobData, CreateJobErrors, CreateJobResponses, GetJobResultsData, GetJobResultsErrors, GetJobResultsResponses, GetJobStatusData, GetJobStatusErrors, GetJobStatusResponses, HealthCheckData, HealthCheckResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Health Check
 *
 * Health check endpoint
 */
export const healthCheck = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckData, ThrowOnError>): RequestResult<HealthCheckResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthCheckResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Create a processing job (object_detect or scene_detect)
 *
 * Create a video processing job. The job_type field selects which
 * processing pipeline to run, and params holds type-specific options.
 */
export const createJob = <ThrowOnError extends boolean = false>(options: Options<CreateJobData, ThrowOnError>): RequestResult<CreateJobResponses, CreateJobErrors, ThrowOnError> => (options.client ?? client).post<CreateJobResponses, CreateJobErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/job/create',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get the status of a job
 *
 * Get the status of a processing job
 */
export const getJobStatus = <ThrowOnError extends boolean = false>(options: Options<GetJobStatusData, ThrowOnError>): RequestResult<GetJobStatusResponses, GetJobStatusErrors, ThrowOnError> => (options.client ?? client).get<GetJobStatusResponses, GetJobStatusErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/status/{job_id}',
    ...options
});

/**
 * Get the results of a completed job
 */
export const getJobResults = <ThrowOnError extends boolean = false>(options: Options<GetJobResultsData, ThrowOnError>): RequestResult<GetJobResultsResponses, GetJobResultsErrors, ThrowOnError> => (options.client ?? client).get<GetJobResultsResponses, GetJobResultsErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/job/{job_id}/results',
    ...options
});
