// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type { CreateAnalysisJobData, CreateAnalysisJobErrors, CreateAnalysisJobResponses, GetJobResultsData, GetJobResultsErrors, GetJobResultsResponses, GetJobStatusData, GetJobStatusErrors, GetJobStatusResponses, HealthCheckData, HealthCheckResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health Check
 *
 * Health check endpoint
 */
export const healthCheck = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Create an analysis task for a video
 *
 * Start video analysis on a video
 */
export const createAnalysisJob = <ThrowOnError extends boolean = false>(options: Options<CreateAnalysisJobData, ThrowOnError>) => (options.client ?? client).post<CreateAnalysisJobResponses, CreateAnalysisJobErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/job/analyse',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get the status of a detection job
 *
 * Get the status of a detection job
 */
export const getJobStatus = <ThrowOnError extends boolean = false>(options: Options<GetJobStatusData, ThrowOnError>) => (options.client ?? client).get<GetJobStatusResponses, GetJobStatusErrors, ThrowOnError>({ url: '/status/{job_id}', ...options });

/**
 * Get the results of a completed analysis job
 */
export const getJobResults = <ThrowOnError extends boolean = false>(options: Options<GetJobResultsData, ThrowOnError>) => (options.client ?? client).get<GetJobResultsResponses, GetJobResultsErrors, ThrowOnError>({ url: '/job/{job_id}/results', ...options });
