// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://raw.githubusercontent.com' | (string & {});
};

export type Webhooks = JobCompletedjobCompletedPostWebhookRequest;

/**
 * AnalysisRequest
 */
export type AnalysisRequest = {
    /**
     * External Id
     *
     * Project identifier
     */
    external_id: string;
    /**
     * Video Url
     *
     * URL or path to video file
     */
    video_url: string;
    /**
     * Similarity Threshold
     *
     * Similarity threshold for object tracking
     */
    similarity_threshold?: number;
    /**
     * Callback Url
     *
     * Callback URL for job completion notifications
     */
    callback_url?: string | null;
};

/**
 * AnalysisResponse
 */
export type AnalysisResponse = {
    /**
     * Job Id
     */
    job_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Queue Position
     */
    queue_position: number;
    /**
     * Message
     */
    message: string;
    /**
     * Callback Url
     */
    callback_url?: string | null;
};

/**
 * BoundingBoxModel
 */
export type BoundingBoxModel = {
    /**
     * X
     */
    x: number;
    /**
     * Y
     */
    y: number;
    /**
     * Width
     */
    width: number;
    /**
     * Height
     */
    height: number;
};

/**
 * DetectionFrameModel
 */
export type DetectionFrameModel = {
    /**
     * Frame Idx
     */
    frame_idx: number;
    /**
     * Timestamp
     */
    timestamp: number;
    /**
     * Objects
     */
    objects: Array<DetectionObjectModel>;
};

/**
 * DetectionObjectModel
 */
export type DetectionObjectModel = {
    /**
     * Id
     */
    id: string;
    /**
     * Class Name
     */
    class_name: string;
    /**
     * Confidence
     */
    confidence: number;
    bbox: BoundingBoxModel;
    /**
     * Thumbnail
     */
    thumbnail: string;
};

/**
 * DetectionResultsModel
 */
export type DetectionResultsModel = {
    /**
     * Version
     */
    version: string;
    metadata: ResultsMetadataModel;
    /**
     * Frames
     */
    frames: Array<DetectionFrameModel>;
};

/**
 * DetectionStatisticsModel
 */
export type DetectionStatisticsModel = {
    /**
     * Total Detections
     */
    total_detections?: number | null;
    /**
     * Person Detections
     */
    person_detections?: number | null;
    /**
     * Person With Face
     */
    person_with_face?: number | null;
    /**
     * Person Without Face
     */
    person_without_face?: number | null;
    /**
     * Other Detections
     */
    other_detections?: number | null;
    /**
     * Class Counts
     */
    class_counts?: {
        [key: string]: number;
    } | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 */
export type HealthResponse = {
    /**
     * Version
     */
    version: string;
    /**
     * Status
     */
    status: string;
    /**
     * Timestamp
     */
    timestamp: string;
    job_stats?: JobStats | null;
    /**
     * Error
     */
    error?: string | null;
};

/**
 * JobCompletedWebhook
 */
export type JobCompletedWebhook = {
    /**
     * Job Id
     */
    job_id: string;
    /**
     * External Id
     */
    external_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Timestamp
     */
    timestamp: Date;
};

/**
 * JobResultsResponse
 */
export type JobResultsResponse = {
    /**
     * Status
     */
    status: string;
    data?: DetectionResultsModel | null;
    /**
     * Error Message
     */
    error_message?: string | null;
};

/**
 * JobStats
 */
export type JobStats = {
    /**
     * Queued
     */
    queued: number;
    /**
     * Processing
     */
    processing: number;
    /**
     * Completed
     */
    completed: number;
    /**
     * Failed
     */
    failed: number;
};

/**
 * JobStatusResponse
 */
export type JobStatusResponse = {
    /**
     * Job Id
     */
    job_id: string;
    /**
     * External Id
     */
    external_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Progress
     */
    progress: number;
    /**
     * Queue Position
     */
    queue_position?: number;
    /**
     * Estimated Wait Time
     */
    estimated_wait_time?: string;
    /**
     * Start Time
     */
    start_time?: string | null;
    /**
     * End Time
     */
    end_time?: string | null;
    /**
     * Error Message
     */
    error_message?: string | null;
};

/**
 * ProcessingMetadataModel
 */
export type ProcessingMetadataModel = {
    /**
     * Start Time
     */
    start_time?: string | null;
    /**
     * End Time
     */
    end_time?: string | null;
    /**
     * Duration Seconds
     */
    duration_seconds?: number | null;
    /**
     * Frames Processed
     */
    frames_processed?: number | null;
    /**
     * Frames With Detections
     */
    frames_with_detections?: number | null;
    /**
     * Processing Speed
     */
    processing_speed?: number | null;
    detection_statistics?: DetectionStatisticsModel | null;
};

/**
 * ResultsMetadataModel
 */
export type ResultsMetadataModel = {
    video: VideoMetadataModel;
    sprite: SpriteMetadataModel;
    processing: ProcessingMetadataModel;
};

/**
 * SpriteMetadataModel
 */
export type SpriteMetadataModel = {
    /**
     * Path
     */
    path: string;
    /**
     * Thumbnail Size
     */
    thumbnail_size: Array<number>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VideoMetadataModel
 */
export type VideoMetadataModel = {
    /**
     * Fps
     */
    fps: number;
    /**
     * Frame Count
     */
    frame_count: number;
    /**
     * Width
     */
    width: number;
    /**
     * Height
     */
    height: number;
    /**
     * Source
     */
    source: string;
};

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type HealthCheckHealthGetResponse = HealthCheckHealthGetResponses[keyof HealthCheckHealthGetResponses];

export type CreateAnalysisTaskJobAnalysePostData = {
    body: AnalysisRequest;
    path?: never;
    query?: never;
    url: '/job/analyse';
};

export type CreateAnalysisTaskJobAnalysePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAnalysisTaskJobAnalysePostError = CreateAnalysisTaskJobAnalysePostErrors[keyof CreateAnalysisTaskJobAnalysePostErrors];

export type CreateAnalysisTaskJobAnalysePostResponses = {
    /**
     * Successful Response
     */
    202: AnalysisResponse;
};

export type CreateAnalysisTaskJobAnalysePostResponse = CreateAnalysisTaskJobAnalysePostResponses[keyof CreateAnalysisTaskJobAnalysePostResponses];

export type GetJobStatusStatusJobIdGetData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/status/{job_id}';
};

export type GetJobStatusStatusJobIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetJobStatusStatusJobIdGetError = GetJobStatusStatusJobIdGetErrors[keyof GetJobStatusStatusJobIdGetErrors];

export type GetJobStatusStatusJobIdGetResponses = {
    /**
     * Successful Response
     */
    200: JobStatusResponse;
};

export type GetJobStatusStatusJobIdGetResponse = GetJobStatusStatusJobIdGetResponses[keyof GetJobStatusStatusJobIdGetResponses];

export type GetJobResultsJobJobIdResultsGetData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/job/{job_id}/results';
};

export type GetJobResultsJobJobIdResultsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetJobResultsJobJobIdResultsGetError = GetJobResultsJobJobIdResultsGetErrors[keyof GetJobResultsJobJobIdResultsGetErrors];

export type GetJobResultsJobJobIdResultsGetResponses = {
    /**
     * Successful Response
     */
    200: JobResultsResponse;
};

export type GetJobResultsJobJobIdResultsGetResponse = GetJobResultsJobJobIdResultsGetResponses[keyof GetJobResultsJobJobIdResultsGetResponses];

export type JobCompletedjobCompletedPostWebhookPayload = JobCompletedWebhook;

export type JobCompletedjobCompletedPostWebhookRequest = {
    body: JobCompletedjobCompletedPostWebhookPayload;
    key: 'job-completed';
    path?: never;
    query?: never;
};
